/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeMethods */

#ifndef _Included_NativeMethods
#define _Included_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeMethods
 * Method:    crashMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeMethods_crashMemory
  (JNIEnv *, jobject);

/*
 * Class:     NativeMethods
 * Method:    allocateMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_NativeMethods_allocateMemory
  (JNIEnv *, jobject);

/*
 * Class:     NativeMethods
 * Method:    crashWithStackTrace
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeMethods_crashWithStackTrace
  (JNIEnv *, jobject);

/*
 * Class:     NativeMethods
 * Method:    getStringLength
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_NativeMethods_getStringLength
  (JNIEnv *, jobject, jstring);

/*
 * Class:     NativeMethods
 * Method:    callObjectMethod
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_NativeMethods_callObjectMethod
  (JNIEnv *, jobject, jobject);

/*
 * Class:     NativeMethods
 * Method:    changeObjectField
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_NativeMethods_changeObjectField
  (JNIEnv *, jobject, jobject);

/*
 * Class:     NativeMethods
 * Method:    allocateStructure
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_NativeMethods_allocateStructure
  (JNIEnv *, jobject);

/*
 * Class:     NativeMethods
 * Method:    getStructureValue
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_NativeMethods_getStructureValue
  (JNIEnv *, jobject, jlong);

/*
 * Class:     NativeMethods
 * Method:    freeStructure
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_NativeMethods_freeStructure
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
